# Generated by Django 6.0.7 on 2026-09-07 02:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('General Medicine', 'General Medicine / Physician'), ('Cardiology', 'Cardiology (Heart & Blood Vessels)'), ('Dermatology', 'Dermatology (Skin, Hair, Nails)'), ('Neurology', 'Neurology (Brain & Nervous System)'), ('Orthopedics', 'Orthopedics (Bones & Joints)'), ('Pediatrics', 'Pediatrics (Children Health)'), ('Pulmonology', 'Pulmonology (Lungs & Respiratory)'), ('Gastroenterology', 'Gastroenterology (Digestive System)'), ('Endocrinology', 'Endocrinology (Diabetes & Hormones)'), ('Psychiatry', 'Psychiatry & Mental Health'), ('ENT', 'ENT (Ear, Nose & Throat)'), ('Ophthalmology', 'Ophthalmology (Eye Care)'), ('Gynecology', 'Gynecology & Obstetrics')], default='General Medicine', max_length=100)),
                ('qualification', models.CharField(help_text='E.g., MBBS, MD, MS, FACC', max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('hospital_or_clinic', models.CharField(help_text='Hospital or Clinic Name', max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('bio', models.TextField(blank=True, null=True)),
                ('available_days', models.CharField(default='Monday, Tuesday, Wednesday, Thursday, Friday', help_text='Comma-separated days doctor is available', max_length=200)),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_available', models.BooleanField(default=True)),
                ('is_approved_by_admin', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Known past medical history, surgeries, etc.', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Drug or food allergies', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='E.g. Diabetes, Hypertension, Asthma', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Any ongoing medications', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
