# Generated by Django 6.0.7 on 2026-09-07 02:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='BPM (beats per min)', null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='Systolic BP (mmHg)', null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='Diastolic BP (mmHg)', null=True)),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=1, help_text='Blood Sugar (mg/dL)', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='Weight (kg)', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='Height (cm)', max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature (°F)', max_digits=4, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='SpO2 (%)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('heart_rate', 'Heart Rate'), ('blood_sugar', 'Blood Sugar'), ('oxygen', 'Oxygen SpO2'), ('temperature', 'Temperature'), ('general', 'General Health Alert')], default='general', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='health.healthrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='Comma-separated symptoms or summary')),
                ('duration', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild (Manageable with minimal disruption)'), ('moderate', 'Moderate (Noticeable disruption to daily activities)'), ('severe', 'Severe (Intense pain or significant impairment)')], default='mild', max_length=50)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('ai_response_raw', models.TextField(blank=True, null=True)),
                ('possible_concerns', models.TextField(help_text='General health concern categories identified')),
                ('recommended_specialization', models.CharField(default='General Medicine', max_length=100)),
                ('urgency_level', models.CharField(choices=[('routine', 'Routine Care (Schedule when convenient)'), ('consult_soon', 'Consult Soon (Within 1-2 days)'), ('urgent', 'Urgent Medical Attention (Same day recommended)'), ('emergency', 'Emergency Care (Immediate ER / Ambulance)')], default='routine', max_length=50)),
                ('guidance_notes', models.TextField()),
                ('disclaimer', models.TextField(default='NOTICE: This assessment is generated by an AI assistant for general informational and triage guidance only. It is not a clinical diagnosis or medical treatment plan. If you experience severe symptoms like chest pain, severe breathlessness, or stroke signs, call emergency services immediately.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
